name: "Github / Asana Integration"
description: "Adds a PR link to an Asana Ticket and vice versa."
branding:
  icon: "check-circle"
  color: "white"
inputs:
  asana-token:
    description: "Asana Access Token"
    required: true
  github-token:
    description: "Github Token"
    required: true
outputs:
  asana-task:
    description: "Asana Task URL"
runs:
  using: "node12"
  main: "dist/index.js"
